### ISSUE TITLE
JSONException: not close json text, token

### ISSUE THREAD

**Issue by xlioo** [xlioo/scheduling#1]
Version：v1.0  
Error Message:
```
mmtekiMacBook-Pro:target neo$ java -jar scheduling-1.0-SNAPSHOT-jar-with-dependencies.jar {\"employees\":{\"FR\":[\"张明明\",\"高翔\"],\"FI\":[\"叶兵\",\"思涛\",\"邹明伟\",\"肖雨豪\",\"希兴杰\"],\"Data\":[\"徐昕平\",\"胡佳斌\",\"夏永刚\",\"韩文强\"],\"DFX\":[],\"App\":[\"谭林\",\"陈霄阳\"]},\"history\":{\"startDate\":\"2020-01-30\",\"plan\":[\"张明明\",\"叶兵\",\"徐昕平\",\"夏永刚\"]},\"ScoreRules\":{\"weak\":[30,25,10,15,15,10,20],\"specialDate\":{\"2020-01-30\":40,\"2020-01-31\":50,\"2020-02-03\":100}}}
args[0]: "employees":"FR":["张明明"
Exception in thread "main" com.alibaba.fastjson.JSONException: not close json text, token : :
	at com.alibaba.fastjson.parser.DefaultJSONParser.close(DefaultJSONParser.java:1526)
	at com.alibaba.fastjson.JSON.parse(JSON.java:174)
	at com.alibaba.fastjson.JSON.parse(JSON.java:180)
	at com.alibaba.fastjson.JSON.parse(JSON.java:149)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:241)
	at com.xlioo.scheduling.Scheduling.main(Scheduling.java:30)
```

**Comment by xlioo** [comment]
There is a comma ", "in json, which causes the json to be split into two arguments.
use this 
```shell
java -jar scheduling-1.0-SNAPSHOT-jar-with-dependencies.jar {\"employees\":{\"FR\":[\"张明明\"\,\"高翔\"]\,\"FI\":[\"叶兵\"\,\"思涛\"\,\"邹明伟\"\,\"肖雨豪\"\,\"希兴杰\"]\,\"Data\":[\"徐昕平\"\,\"胡佳斌\"\,\"夏永刚\"\,\"韩文强\"]\,\"DFX\":[]\,\"App\":[\"谭林\"\,\"陈霄阳\"]}\,\"history\":{\"startDate\":\"2020-01-30\"\,\"plan\":[\"张明明\"\,\"叶兵\"\,\"徐昕平\"\,\"夏永刚\"]}\,\"ScoreRules\":{\"weak\":[30\,25\,10\,15\,15\,10\,20]\,\"specialDate\":{\"2020-01-30\":40\,\"2020-01-31\":50\,\"2020-02-03\":100}}}
```
